import numpy as np
import scipy as sp
import torch
import torchaudio
import torchaudio.transforms as T

def denoise(self, hop_length_in_seconds:float=0.02, window_length_in_seconds:float=0.1, threshold_softness:float=3.0, stat_mode="median", verbose:bool=False)->np.array:
    '''
    This method is used to denoise the audio file and it returns a copy of the denoised audio array.
    It performs a windowing function to denoise segments by comparing them to a threshold value.
    This threshold value is calculated using a statistical mode on the amplitude envelope generated by hilbert transform of the signal.
    If the calcutated statistic of the amplitude envelope of the previous and next segment of the current segment in the windowing function is less than the threshold,
    this probably means the current segment is noise (as there is an amplitude difference and usually noise has a lower amplitude) and it will be silenced.

    Parameters
    ----------
    hop_length_in_seconds:float (optional)
            the hop length of the denoising windowing function. if not provided, the default value is 0.02. it is advised to keep this number as default or at most the same as `window_length_in_seconds`

    window_length_in_seconds:float (optional)
            the length of the denoising windowing function. if not provided, the default value is 0.1 second.

    threshold_softness:float (optional)
            the softness of the threshold. if this number is high, the threshold will be lower and therefore, the low amplitude areas may persist.

    stat_mode:str (optional)
            the statistical mode to use to calculate from the amplitude envelope of the signal. if not provided, the default value is "median".
            median is recommended as it's not affected by outliers and is faster to calculate.

    verbose:bool (optional)
            whether to print the progress of the denoising process. if not provided, the default value is False

    Returns
    ----------
    np.array: The denoised copy of the audio file

    Raises
    ----------
    AssertionError

    '''
    assert isinstance(window_length_in_seconds, float) and window_length_in_seconds > 0 and window_length_in_seconds*self.sample_rate < len(self.__wav_file), f"window_length_in_seconds must be a positive float and less than {self.wav_duration_in_seconds} seconds"
    assert isinstance(hop_length_in_seconds, float) and hop_length_in_seconds > 0 and hop_length_in_seconds <=  window_length_in_seconds, f"hop_length_in_seconds must be a positive float and at most {window_length_in_seconds} seconds"
    assert isinstance(threshold_softness, float) and threshold_softness > 0, f"threshold_softness must be a positive float"
    assert isinstance(verbose, bool), f"verbose must be a boolean. Found {type(verbose).__name__}"
    stat_mode = str.lower(stat_mode).replace(" ", "")
    assert isinstance(stat_mode, str) and stat_mode in ["median", "mean", "mode"], print(f"expected 'mean', 'median' or 'mode' for `stat_mode` but received: '{stat_mode}'")


    def amps_reducer_function(amps):
        if stat_mode == "median":
            return np.median(amps)
        elif stat_mode == "mean":
            return np.mean(amps)
        elif stat_mode == "mode":
            return sp.stats.mode(amps)

    wav = np.copy(self.__wav_file)
    amp, freq = self.__hilbert_metrics()
    amp_stat = amps_reducer_function(amp)
    threshold = amp_stat/threshold_softness #calculates the threshold
    hop_length = int(hop_length_in_seconds*self.sample_rate) #converts the hop length in seconds to number of samples
    window_length = int(window_length_in_seconds*self.sample_rate) #converts the window length in seconds to number of samples
    muted_segments_count = 0

    for i in range(window_length, len(wav)-window_length, hop_length): #iterates over the audio file and moves the window by hop_length samples
        segment = amp[i: i+window_length] #gets the current segment of the window
        previous_segment_stat = amps_reducer_function(amp[i-window_length: i]) #calculates the amplitude stats of the previous segment
        next_segment_stat = amps_reducer_function(amp[i+window_length: i+window_length*2]) #calculates the amplitude stats of the next segment

        if previous_segment_stat < threshold and next_segment_stat < threshold:       
            segment *= 0.0
            fade_next = np.linspace(0, 1, len(wav[i+window_length: i+window_length*2]))
            if i == window_length: #if it's the first sample of the window, silence the previous and current segments and fade in the next segment linearly
                wav[i-window_length: i] = segment
                wav[i: i+window_length] = segment
                wav[i+window_length: i+window_length*2] *= fade_next
            else: #oterwise, fade out the previous segment linearly, mute the current segment and fade in the next segment linearly 
                fade_prev = np.linspace(1, 0, len(wav[i-window_length: i]))
                wav[i-window_length: i] *= fade_prev
                wav[i: i+window_length] = segment
                wav[i+window_length: i+window_length*2] *= fade_next
    
            #fading makes the denoising more realistic

        muted_segments_count +=	 1
        
    if verbose: print(f"Denoising completed! muted {muted_segments_count} segments")
    return wav


def spectrogram_to_wav(spectrogram_magnitude, sample_rate, n_fft, hop_length, win_length, original_audio_length):
    # Ensure spectrogram_magnitude is a 3D tensor [batch_size, freq, time]
    # In this context, we are processing one spectrogram at a time, so batch_size=1
    print(f"Initial spectrogram_magnitude shape (inside func): {spectrogram_magnitude.shape}")

    if spectrogram_magnitude.dim() == 2:
        spectrogram_magnitude = spectrogram_magnitude.unsqueeze(0) # [1, freq, time]
    elif spectrogram_magnitude.dim() != 3:
        raise ValueError(f"Expected 2D or 3D spectrogram_magnitude, got {spectrogram_magnitude.dim()}D")

    complex_spectrogram = spectrogram_magnitude.to(torch.cdouble)
    print(f"Complex spectrogram shape before inverse_spectrogram_transform: {complex_spectrogram.shape}")

    inverse_spectrogram_transform = T.InverseSpectrogram(
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length
        # window_fn=torch.hann_window # Default is hann_window, explicitly setting if needed for consistency
    )

    # Pass the inferred length
    waveform = inverse_spectrogram_transform(complex_spectrogram, length=original_audio_length)
    print(waveform.dim())
    print(waveform.shape)
    return waveform
